// Generated by tools/convert-schema.mjs from the upstream schema. Do not edit: rerun `npm run schema`.
// Upstream code reads these from information_schema.

export interface ForeignKey {
    table: string;
    column: string;
    references: string;
    referencedColumn: string;
}

/** Each game table's columns, with their upstream (MariaDB) types: int, varchar, date, datetime, decimal, enum... */
export const COLUMNS: Record<string, Record<string, string>> = {
    "game_anthro_skills": {
        "anthro_id": "int",
        "skill_id": "int",
        "practice": "int"
    },
    "game_anthros": {
        "id": "int",
        "owner_id": "int",
        "player_id": "int",
        "name": "varchar",
        "gender_id": "int",
        "species_id": "int",
        "birthdate": "date",
        "fertile_on": "date",
        "fertile_until": "date",
        "sire_id": "int",
        "dam_id": "int",
        "breeding_id": "int",
        "created_at": "datetime",
        "fertile_weekday": "tinyint",
        "max_cubs": "tinyint",
        "urge_rise": "tinyint",
        "debt": "bigint",
        "debt_rate": "bigint",
        "debt_since": "datetime",
        "title_rank": "tinyint",
        "title_since": "datetime",
        "liege_id": "int",
        "wage": "bigint",
        "hire_breedable": "tinyint",
        "employer_id": "int",
        "employed_wage": "bigint",
        "employed_since": "datetime",
        "paid_until": "date",
        "lifespan_weeks": "smallint",
        "died_at": "datetime",
        "young": "tinyint",
        "spouse_of": "int",
        "title_by_land": "tinyint",
        "granted_rank": "tinyint",
        "tax_rate": "tinyint",
        "tax_balance": "decimal",
        "tax_overdue_since": "date",
        "trade_occupation_id": "int",
        "trade_recipe_id": "int",
        "seeking_occupation_id": "int",
        "hungry_on": "date",
        "standard_schedule_id": "int"
    },
    "game_auctions": {
        "id": "int",
        "anthro_id": "int",
        "anthro_name": "varchar",
        "seller_id": "int",
        "seller_anthro_id": "int",
        "starting_bid": "bigint",
        "buy_now": "bigint",
        "ends_at": "datetime",
        "status": "enum",
        "winner_id": "int",
        "final_price": "bigint",
        "created_at": "datetime",
        "closed_at": "datetime"
    },
    "game_baronies": {
        "id": "int",
        "name": "varchar",
        "holder_anthro_id": "int",
        "created_at": "datetime"
    },
    "game_barony_parts": {
        "id": "int",
        "barony_id": "int",
        "name": "varchar",
        "kind": "enum",
        "manager_anthro_id": "int"
    },
    "game_bids": {
        "id": "bigint",
        "auction_id": "int",
        "bidder_id": "int",
        "anthro_id": "int",
        "amount": "bigint",
        "created_at": "datetime"
    },
    "game_breeding_groups": {
        "id": "int",
        "name": "varchar",
        "owner_anthro_id": "int",
        "access": "enum",
        "created_by": "int",
        "created_at": "datetime",
        "rolled_through": "date"
    },
    "game_breedings": {
        "id": "int",
        "sire_id": "int",
        "dam_id": "int",
        "litter_id": "int",
        "bred_at": "datetime",
        "bred_by": "int",
        "owner_id": "int",
        "forced": "tinyint",
        "barren_reason": "varchar",
        "group_id": "int"
    },
    "game_building_types": {
        "id": "int",
        "name": "varchar",
        "days": "int",
        "acres": "decimal",
        "sort_order": "int"
    },
    "game_buildings": {
        "id": "int",
        "type_id": "int",
        "parcel_id": "int",
        "progress": "int",
        "started_by": "int",
        "started_at": "datetime",
        "finished_at": "datetime"
    },
    "game_daily": {
        "day": "date",
        "task": "varchar"
    },
    "game_fief_offers": {
        "id": "int",
        "kind": "enum",
        "lord_id": "int",
        "vassal_id": "int",
        "parcel_id": "int",
        "acres": "decimal",
        "rate": "tinyint",
        "created_at": "datetime"
    },
    "game_flirts": {
        "id": "int",
        "from_anthro_id": "int",
        "to_anthro_id": "int",
        "message": "varchar",
        "times": "tinyint",
        "status": "enum",
        "litter": "tinyint",
        "barren_reason": "varchar",
        "created_by": "int",
        "created_at": "datetime",
        "answered_at": "datetime"
    },
    "game_genders": {
        "id": "int",
        "name": "varchar",
        "is_male": "tinyint",
        "is_female": "tinyint",
        "presents_as": "enum",
        "birth_weight": "int",
        "sort_order": "int"
    },
    "game_goods": {
        "anthro_id": "int",
        "good": "varchar",
        "quantity": "bigint"
    },
    "game_group_members": {
        "group_id": "int",
        "anthro_id": "int",
        "joined_at": "datetime"
    },
    "game_group_requests": {
        "id": "int",
        "group_id": "int",
        "anthro_id": "int",
        "kind": "enum",
        "created_by": "int",
        "created_at": "datetime"
    },
    "game_land_listings": {
        "id": "int",
        "parcel_id": "int",
        "acres": "decimal",
        "from_game": "tinyint",
        "seller_anthro_id": "int",
        "price": "bigint",
        "status": "enum",
        "buyer_anthro_id": "int",
        "created_by": "int",
        "created_at": "datetime",
        "closed_at": "datetime"
    },
    "game_ledger": {
        "id": "bigint",
        "anthro_id": "int",
        "amount": "bigint",
        "balance_after": "bigint",
        "reason": "varchar",
        "auction_id": "int",
        "created_at": "datetime",
        "created_by": "int"
    },
    "game_litters": {
        "id": "int",
        "dam_id": "int",
        "bred_on": "date",
        "due_on": "date",
        "born_at": "datetime"
    },
    "game_market_goods": {
        "good": "varchar",
        "name": "varchar",
        "buy_price": "int",
        "sell_price": "int",
        "sort_order": "int",
        "edible": "tinyint"
    },
    "game_names": {
        "id": "int",
        "name": "varchar",
        "is_male": "tinyint",
        "is_female": "tinyint"
    },
    "game_notifications": {
        "id": "bigint",
        "anthro_id": "int",
        "user_id": "int",
        "kind": "enum",
        "from_anthro_id": "int",
        "body": "text",
        "link": "varchar",
        "created_at": "datetime",
        "read_at": "datetime",
        "deleted_at": "datetime",
        "deleted_by": "int",
        "sent_by": "int",
        "times": "int",
        "group_key": "char"
    },
    "game_occupations": {
        "id": "int",
        "title": "varchar",
        "skill_id": "int",
        "sort_order": "int",
        "era": "varchar"
    },
    "game_parcels": {
        "id": "int",
        "anthro_id": "int",
        "acres": "decimal",
        "created_at": "datetime",
        "barony_id": "int",
        "part_id": "int",
        "held_of": "int",
        "tenure": "varchar"
    },
    "game_preferences": {
        "user_id": "int",
        "era": "varchar",
        "time_rate": "decimal"
    },
    "game_proposals": {
        "id": "int",
        "head_id": "int",
        "spouse_id": "int",
        "from_id": "int",
        "status": "enum",
        "created_at": "datetime",
        "answered_at": "datetime"
    },
    "game_ranks": {
        "rank": "tinyint",
        "name": "varchar",
        "female_name": "varchar",
        "is_noble": "tinyint",
        "is_hereditary": "tinyint"
    },
    "game_recipe_goods": {
        "recipe_id": "int",
        "good": "varchar",
        "quantity": "smallint",
        "role": "enum"
    },
    "game_recipes": {
        "id": "int",
        "occupation_id": "int",
        "name": "varchar",
        "needs_acres": "decimal",
        "sort_order": "int"
    },
    "game_renames": {
        "id": "int",
        "anthro_id": "int",
        "old_name": "varchar",
        "new_name": "varchar",
        "renamed_at": "datetime",
        "renamed_by": "int"
    },
    "game_reset_requests": {
        "id": "int",
        "user_id": "int",
        "anthro_id": "int",
        "reason": "varchar",
        "status": "enum",
        "requested_at": "datetime",
        "handled_by": "int",
        "handled_at": "datetime"
    },
    "game_saves": {
        "id": "int",
        "name": "varchar",
        "anthros": "int",
        "data": "longblob",
        "created_by": "int",
        "created_at": "datetime"
    },
    "game_schedule_days": {
        "anthro_id": "int",
        "day": "date",
        "activity": "enum",
        "partner_anthro_id": "int",
        "group_id": "int",
        "skill_id": "int",
        "occupation_id": "int",
        "recipe_id": "int",
        "part_id": "int",
        "building_id": "int",
        "set_by": "int"
    },
    "game_schedule_log": {
        "anthro_id": "int",
        "day": "date",
        "activity": "enum",
        "outcome": "varchar"
    },
    "game_schedule_weekly": {
        "anthro_id": "int",
        "weekday": "tinyint",
        "activity": "enum",
        "partner_anthro_id": "int",
        "group_id": "int",
        "skill_id": "int",
        "occupation_id": "int",
        "recipe_id": "int",
        "part_id": "int",
        "building_id": "int",
        "set_by": "int"
    },
    "game_settings": {
        "name": "varchar",
        "value": "varchar"
    },
    "game_skills": {
        "id": "int",
        "name": "varchar",
        "sort_order": "int",
        "era": "varchar"
    },
    "game_species": {
        "id": "int",
        "name": "varchar",
        "group_id": "int"
    },
    "game_species_groups": {
        "id": "int",
        "name": "varchar",
        "sort_order": "int"
    },
    "game_standard_days": {
        "schedule_id": "int",
        "weekday": "tinyint",
        "activity": "enum",
        "partner_anthro_id": "int",
        "group_id": "int",
        "skill_id": "int",
        "occupation_id": "int",
        "recipe_id": "int",
        "part_id": "int",
        "building_id": "int",
        "set_by": "int"
    },
    "game_standard_schedules": {
        "id": "int",
        "user_id": "int",
        "name": "varchar",
        "created_at": "datetime"
    },
    "game_transfers": {
        "id": "int",
        "anthro_id": "int",
        "from_owner_id": "int",
        "to_owner_id": "int",
        "transferred_at": "datetime",
        "transferred_by": "int",
        "note": "varchar"
    },
    "game_wallets": {
        "anthro_id": "int",
        "balance": "bigint",
        "created_at": "datetime"
    }
};

export const FOREIGN_KEYS: ForeignKey[] = [
    {
        "table": "game_anthro_skills",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthro_skills",
        "column": "skill_id",
        "references": "game_skills",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "breeding_id",
        "references": "game_breedings",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "spouse_of",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "trade_occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "seeking_occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "standard_schedule_id",
        "references": "game_standard_schedules",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "trade_recipe_id",
        "references": "game_recipes",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "owner_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "employer_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "gender_id",
        "references": "game_genders",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "species_id",
        "references": "game_species",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "sire_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "dam_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "liege_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_anthros",
        "column": "player_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_auctions",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_auctions",
        "column": "seller_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_auctions",
        "column": "winner_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_auctions",
        "column": "seller_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_baronies",
        "column": "holder_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_barony_parts",
        "column": "barony_id",
        "references": "game_baronies",
        "referencedColumn": "id"
    },
    {
        "table": "game_barony_parts",
        "column": "manager_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_bids",
        "column": "auction_id",
        "references": "game_auctions",
        "referencedColumn": "id"
    },
    {
        "table": "game_bids",
        "column": "bidder_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_bids",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_breeding_groups",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_breeding_groups",
        "column": "owner_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_breedings",
        "column": "sire_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_breedings",
        "column": "dam_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_breedings",
        "column": "bred_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_breedings",
        "column": "litter_id",
        "references": "game_litters",
        "referencedColumn": "id"
    },
    {
        "table": "game_breedings",
        "column": "owner_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_buildings",
        "column": "type_id",
        "references": "game_building_types",
        "referencedColumn": "id"
    },
    {
        "table": "game_buildings",
        "column": "parcel_id",
        "references": "game_parcels",
        "referencedColumn": "id"
    },
    {
        "table": "game_buildings",
        "column": "started_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_fief_offers",
        "column": "lord_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_fief_offers",
        "column": "vassal_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_fief_offers",
        "column": "parcel_id",
        "references": "game_parcels",
        "referencedColumn": "id"
    },
    {
        "table": "game_flirts",
        "column": "from_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_flirts",
        "column": "to_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_flirts",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_goods",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_group_members",
        "column": "group_id",
        "references": "game_breeding_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_group_members",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_group_requests",
        "column": "group_id",
        "references": "game_breeding_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_group_requests",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_group_requests",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_land_listings",
        "column": "parcel_id",
        "references": "game_parcels",
        "referencedColumn": "id"
    },
    {
        "table": "game_land_listings",
        "column": "seller_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_land_listings",
        "column": "buyer_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_land_listings",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_ledger",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_ledger",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_litters",
        "column": "dam_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_notifications",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_notifications",
        "column": "user_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_notifications",
        "column": "from_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_notifications",
        "column": "deleted_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_notifications",
        "column": "sent_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_occupations",
        "column": "skill_id",
        "references": "game_skills",
        "referencedColumn": "id"
    },
    {
        "table": "game_parcels",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_parcels",
        "column": "barony_id",
        "references": "game_baronies",
        "referencedColumn": "id"
    },
    {
        "table": "game_parcels",
        "column": "part_id",
        "references": "game_barony_parts",
        "referencedColumn": "id"
    },
    {
        "table": "game_parcels",
        "column": "held_of",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_preferences",
        "column": "user_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_proposals",
        "column": "head_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_proposals",
        "column": "spouse_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_proposals",
        "column": "from_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_recipe_goods",
        "column": "recipe_id",
        "references": "game_recipes",
        "referencedColumn": "id"
    },
    {
        "table": "game_recipe_goods",
        "column": "good",
        "references": "game_market_goods",
        "referencedColumn": "good"
    },
    {
        "table": "game_recipes",
        "column": "occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_renames",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_renames",
        "column": "renamed_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_reset_requests",
        "column": "user_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_reset_requests",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_reset_requests",
        "column": "handled_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_saves",
        "column": "created_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "partner_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "group_id",
        "references": "game_breeding_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "skill_id",
        "references": "game_skills",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "set_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "part_id",
        "references": "game_barony_parts",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "building_id",
        "references": "game_buildings",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_days",
        "column": "recipe_id",
        "references": "game_recipes",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_log",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "partner_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "group_id",
        "references": "game_breeding_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "skill_id",
        "references": "game_skills",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "set_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "part_id",
        "references": "game_barony_parts",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "building_id",
        "references": "game_buildings",
        "referencedColumn": "id"
    },
    {
        "table": "game_schedule_weekly",
        "column": "recipe_id",
        "references": "game_recipes",
        "referencedColumn": "id"
    },
    {
        "table": "game_species",
        "column": "group_id",
        "references": "game_species_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "schedule_id",
        "references": "game_standard_schedules",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "partner_anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "group_id",
        "references": "game_breeding_groups",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "skill_id",
        "references": "game_skills",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "occupation_id",
        "references": "game_occupations",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "part_id",
        "references": "game_barony_parts",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "building_id",
        "references": "game_buildings",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "set_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_days",
        "column": "recipe_id",
        "references": "game_recipes",
        "referencedColumn": "id"
    },
    {
        "table": "game_standard_schedules",
        "column": "user_id",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_transfers",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_transfers",
        "column": "transferred_by",
        "references": "users",
        "referencedColumn": "id"
    },
    {
        "table": "game_transfers",
        "column": "from_owner_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_transfers",
        "column": "to_owner_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    },
    {
        "table": "game_wallets",
        "column": "anthro_id",
        "references": "game_anthros",
        "referencedColumn": "id"
    }
];

/** A table's DATE, DATETIME and TIMESTAMP columns, in order. */
export function dateColumns(table: string): string[] {
    return Object.entries(COLUMNS[table] ?? {}).filter(([, type]) => ['date', 'datetime', 'timestamp'].includes(type)).map(([name]) => name);
}
