-- Generated by tools/convert-schema.mjs from the upstream schema. Do not edit: rerun `npm run schema`.

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT COLLATE NOCASE NOT NULL UNIQUE,
    is_admin INTEGER NOT NULL DEFAULT 0,
    is_player INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP())
);

CREATE TABLE game_anthro_skills (
    anthro_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    practice INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (anthro_id, skill_id),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES game_skills (id) ON DELETE CASCADE
);
CREATE INDEX game_anthro_skills__skill_id ON game_anthro_skills (skill_id);

CREATE TABLE game_anthros (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER,
    player_id INTEGER,
    name TEXT COLLATE NOCASE NOT NULL,
    gender_id INTEGER NOT NULL,
    species_id INTEGER,
    birthdate TEXT,
    fertile_on TEXT,
    fertile_until TEXT,
    sire_id INTEGER,
    dam_id INTEGER,
    breeding_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    fertile_weekday INTEGER,
    max_cubs INTEGER,
    urge_rise INTEGER,
    debt INTEGER,
    debt_rate INTEGER NOT NULL DEFAULT 0,
    debt_since TEXT,
    title_rank INTEGER,
    title_since TEXT,
    liege_id INTEGER,
    wage INTEGER,
    hire_breedable INTEGER NOT NULL DEFAULT 1,
    employer_id INTEGER,
    employed_wage INTEGER,
    employed_since TEXT,
    paid_until TEXT,
    lifespan_weeks INTEGER,
    died_at TEXT,
    young INTEGER NOT NULL DEFAULT 0,
    spouse_of INTEGER,
    title_by_land INTEGER NOT NULL DEFAULT 0,
    granted_rank INTEGER,
    tax_rate INTEGER,
    tax_balance REAL NOT NULL DEFAULT 0.00,
    tax_overdue_since TEXT,
    trade_occupation_id INTEGER,
    seeking_occupation_id INTEGER,
    hungry_on TEXT,
    standard_schedule_id INTEGER,
    UNIQUE (player_id),
    FOREIGN KEY (breeding_id) REFERENCES game_breedings (id) ON DELETE SET NULL,
    FOREIGN KEY (spouse_of) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (trade_occupation_id) REFERENCES game_occupations (id) ON DELETE SET NULL,
    FOREIGN KEY (seeking_occupation_id) REFERENCES game_occupations (id) ON DELETE SET NULL,
    FOREIGN KEY (standard_schedule_id) REFERENCES game_standard_schedules (id) ON DELETE SET NULL,
    FOREIGN KEY (owner_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (employer_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (gender_id) REFERENCES game_genders (id),
    FOREIGN KEY (species_id) REFERENCES game_species (id),
    FOREIGN KEY (sire_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (dam_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (liege_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (player_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_anthros__owner_id ON game_anthros (owner_id, name);
CREATE INDEX game_anthros__gender_id ON game_anthros (gender_id);
CREATE INDEX game_anthros__species_id ON game_anthros (species_id);
CREATE INDEX game_anthros__sire_id ON game_anthros (sire_id);
CREATE INDEX game_anthros__dam_id ON game_anthros (dam_id);
CREATE INDEX game_anthros__liege_id ON game_anthros (liege_id);
CREATE INDEX game_anthros__employer_id ON game_anthros (employer_id);
CREATE INDEX game_anthros__breeding_id ON game_anthros (breeding_id);
CREATE INDEX game_anthros__died_at ON game_anthros (died_at);
CREATE INDEX game_anthros__spouse_of ON game_anthros (spouse_of);
CREATE INDEX game_anthros__trade_occupation_id ON game_anthros (trade_occupation_id);
CREATE INDEX game_anthros__seeking_occupation_id ON game_anthros (seeking_occupation_id);
CREATE INDEX game_anthros__standard_schedule_id ON game_anthros (standard_schedule_id);

CREATE TABLE game_auctions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER,
    anthro_name TEXT COLLATE NOCASE NOT NULL,
    seller_id INTEGER,
    seller_anthro_id INTEGER,
    starting_bid INTEGER NOT NULL,
    buy_now INTEGER,
    ends_at TEXT NOT NULL,
    status TEXT CHECK (status IN ('open','sold','unsold','cancelled')) NOT NULL DEFAULT 'open',
    winner_id INTEGER,
    final_price INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    closed_at TEXT,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (winner_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (seller_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_auctions__status ON game_auctions (status, ends_at);
CREATE INDEX game_auctions__anthro_id ON game_auctions (anthro_id);
CREATE INDEX game_auctions__seller_id ON game_auctions (seller_id);
CREATE INDEX game_auctions__winner_id ON game_auctions (winner_id);
CREATE INDEX game_auctions__seller_anthro_id ON game_auctions (seller_anthro_id);

CREATE TABLE game_baronies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    holder_anthro_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    UNIQUE (name),
    FOREIGN KEY (holder_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_baronies__holder_anthro_id ON game_baronies (holder_anthro_id);

CREATE TABLE game_barony_parts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    barony_id INTEGER NOT NULL,
    name TEXT COLLATE NOCASE NOT NULL,
    kind TEXT CHECK (kind IN ('village','town','city','expanse','manor')) NOT NULL,
    manager_anthro_id INTEGER,
    UNIQUE (barony_id, name),
    FOREIGN KEY (barony_id) REFERENCES game_baronies (id) ON DELETE CASCADE,
    FOREIGN KEY (manager_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_barony_parts__manager_anthro_id ON game_barony_parts (manager_anthro_id);

CREATE TABLE game_bids (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    auction_id INTEGER NOT NULL,
    bidder_id INTEGER,
    anthro_id INTEGER,
    amount INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    FOREIGN KEY (auction_id) REFERENCES game_auctions (id) ON DELETE CASCADE,
    FOREIGN KEY (bidder_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_bids__auction_id ON game_bids (auction_id, amount);
CREATE INDEX game_bids__bidder_id ON game_bids (bidder_id);
CREATE INDEX game_bids__anthro_id ON game_bids (anthro_id);

CREATE TABLE game_breeding_groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    owner_anthro_id INTEGER,
    access TEXT CHECK (access IN ('open','request','invite','closed','private')) NOT NULL DEFAULT 'closed',
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    rolled_through TEXT,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (owner_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_breeding_groups__created_by ON game_breeding_groups (created_by);
CREATE INDEX game_breeding_groups__owner_anthro_id ON game_breeding_groups (owner_anthro_id);

CREATE TABLE game_breedings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sire_id INTEGER,
    dam_id INTEGER,
    litter_id INTEGER,
    bred_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    bred_by INTEGER,
    owner_id INTEGER,
    forced INTEGER NOT NULL DEFAULT 0,
    barren_reason TEXT COLLATE NOCASE,
    group_id INTEGER,
    FOREIGN KEY (sire_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (dam_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (bred_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (litter_id) REFERENCES game_litters (id) ON DELETE SET NULL,
    FOREIGN KEY (owner_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_breedings__sire_id ON game_breedings (sire_id);
CREATE INDEX game_breedings__dam_id ON game_breedings (dam_id);
CREATE INDEX game_breedings__bred_by ON game_breedings (bred_by);
CREATE INDEX game_breedings__litter_id ON game_breedings (litter_id);
CREATE INDEX game_breedings__group_id ON game_breedings (group_id);
CREATE INDEX game_breedings__owner_id ON game_breedings (owner_id);

CREATE TABLE game_building_types (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    days INTEGER NOT NULL,
    acres REAL NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);

CREATE TABLE game_buildings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type_id INTEGER NOT NULL,
    parcel_id INTEGER NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0,
    started_by INTEGER,
    started_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    finished_at TEXT,
    FOREIGN KEY (type_id) REFERENCES game_building_types (id),
    FOREIGN KEY (parcel_id) REFERENCES game_parcels (id) ON DELETE CASCADE,
    FOREIGN KEY (started_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_buildings__parcel_id ON game_buildings (parcel_id);
CREATE INDEX game_buildings__type_id ON game_buildings (type_id);
CREATE INDEX game_buildings__started_by ON game_buildings (started_by);

CREATE TABLE game_daily (
    day TEXT NOT NULL,
    task TEXT COLLATE NOCASE NOT NULL,
    PRIMARY KEY (day, task)
);

CREATE TABLE game_fief_offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT CHECK (kind IN ('grant','rate')) NOT NULL,
    lord_id INTEGER NOT NULL,
    vassal_id INTEGER NOT NULL,
    parcel_id INTEGER,
    acres REAL,
    rate INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    FOREIGN KEY (lord_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (vassal_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (parcel_id) REFERENCES game_parcels (id) ON DELETE CASCADE
);
CREATE INDEX game_fief_offers__lord_id ON game_fief_offers (lord_id);
CREATE INDEX game_fief_offers__vassal_id ON game_fief_offers (vassal_id);
CREATE INDEX game_fief_offers__parcel_id ON game_fief_offers (parcel_id);

CREATE TABLE game_flirts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    from_anthro_id INTEGER NOT NULL,
    to_anthro_id INTEGER NOT NULL,
    message TEXT COLLATE NOCASE,
    times INTEGER NOT NULL DEFAULT 1,
    status TEXT CHECK (status IN ('pending','accepted','declined','withdrawn')) NOT NULL DEFAULT 'pending',
    litter INTEGER NOT NULL DEFAULT 0,
    barren_reason TEXT COLLATE NOCASE,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    answered_at TEXT,
    FOREIGN KEY (from_anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (to_anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_flirts__to_anthro_id ON game_flirts (to_anthro_id, status);
CREATE INDEX game_flirts__from_anthro_id ON game_flirts (from_anthro_id);
CREATE INDEX game_flirts__created_by ON game_flirts (created_by);

CREATE TABLE game_genders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    is_male INTEGER NOT NULL DEFAULT 0,
    is_female INTEGER NOT NULL DEFAULT 0,
    presents_as TEXT CHECK (presents_as IN ('male','female','androgynous')) NOT NULL,
    birth_weight INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);

CREATE TABLE game_goods (
    anthro_id INTEGER NOT NULL,
    good TEXT COLLATE NOCASE NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (anthro_id, good),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);

CREATE TABLE game_group_members (
    group_id INTEGER NOT NULL,
    anthro_id INTEGER NOT NULL,
    joined_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    PRIMARY KEY (group_id, anthro_id),
    FOREIGN KEY (group_id) REFERENCES game_breeding_groups (id) ON DELETE CASCADE,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);
CREATE INDEX game_group_members__anthro_id ON game_group_members (anthro_id);

CREATE TABLE game_group_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    anthro_id INTEGER NOT NULL,
    kind TEXT CHECK (kind IN ('request','invite')) NOT NULL,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    UNIQUE (group_id, anthro_id),
    FOREIGN KEY (group_id) REFERENCES game_breeding_groups (id) ON DELETE CASCADE,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_group_requests__anthro_id ON game_group_requests (anthro_id);
CREATE INDEX game_group_requests__created_by ON game_group_requests (created_by);

CREATE TABLE game_land_listings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parcel_id INTEGER NOT NULL,
    acres REAL NOT NULL,
    from_game INTEGER NOT NULL DEFAULT 0,
    seller_anthro_id INTEGER,
    price INTEGER NOT NULL,
    status TEXT CHECK (status IN ('open','sold','cancelled')) NOT NULL DEFAULT 'open',
    buyer_anthro_id INTEGER,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    closed_at TEXT,
    FOREIGN KEY (parcel_id) REFERENCES game_parcels (id) ON DELETE CASCADE,
    FOREIGN KEY (seller_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (buyer_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_land_listings__status ON game_land_listings (status);
CREATE INDEX game_land_listings__parcel_id ON game_land_listings (parcel_id, status);
CREATE INDEX game_land_listings__seller_anthro_id ON game_land_listings (seller_anthro_id);
CREATE INDEX game_land_listings__buyer_anthro_id ON game_land_listings (buyer_anthro_id);
CREATE INDEX game_land_listings__created_by ON game_land_listings (created_by);

CREATE TABLE game_ledger (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    reason TEXT COLLATE NOCASE NOT NULL,
    auction_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    created_by INTEGER,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_ledger__anthro_id ON game_ledger (anthro_id, id);
CREATE INDEX game_ledger__created_by ON game_ledger (created_by);

CREATE TABLE game_litters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dam_id INTEGER NOT NULL,
    bred_on TEXT NOT NULL,
    due_on TEXT NOT NULL,
    born_at TEXT,
    FOREIGN KEY (dam_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);
CREATE INDEX game_litters__dam_id ON game_litters (dam_id);
CREATE INDEX game_litters__born_at ON game_litters (born_at, due_on);

CREATE TABLE game_market_goods (
    good TEXT COLLATE NOCASE NOT NULL,
    name TEXT COLLATE NOCASE NOT NULL,
    buy_price INTEGER,
    sell_price INTEGER,
    sort_order INTEGER NOT NULL DEFAULT 0,
    edible INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (good),
    UNIQUE (name)
);

CREATE TABLE game_names (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    is_male INTEGER NOT NULL DEFAULT 0,
    is_female INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);

CREATE TABLE game_notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER,
    user_id INTEGER,
    kind TEXT CHECK (kind IN ('system','message')) NOT NULL DEFAULT 'system',
    from_anthro_id INTEGER,
    body TEXT COLLATE NOCASE NOT NULL,
    link TEXT COLLATE NOCASE,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    read_at TEXT,
    deleted_at TEXT,
    deleted_by INTEGER,
    sent_by INTEGER,
    times INTEGER NOT NULL DEFAULT 1,
    group_key TEXT COLLATE NOCASE,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (from_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (sent_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_notifications__anthro_id ON game_notifications (anthro_id, read_at);
CREATE INDEX game_notifications__user_id ON game_notifications (user_id, read_at);
CREATE INDEX game_notifications__from_anthro_id ON game_notifications (from_anthro_id);
CREATE INDEX game_notifications__deleted_by ON game_notifications (deleted_by);
CREATE INDEX game_notifications__sent_by ON game_notifications (sent_by);
CREATE INDEX game_notifications__notification_squash ON game_notifications (anthro_id, group_key);
CREATE INDEX game_notifications__notification_squash_user ON game_notifications (user_id, group_key);

CREATE TABLE game_occupations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT COLLATE NOCASE NOT NULL,
    skill_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    era TEXT COLLATE NOCASE,
    UNIQUE (title, skill_id),
    FOREIGN KEY (skill_id) REFERENCES game_skills (id) ON DELETE CASCADE
);
CREATE INDEX game_occupations__skill_id ON game_occupations (skill_id);

CREATE TABLE game_parcels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER,
    acres REAL NOT NULL,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    barony_id INTEGER,
    part_id INTEGER,
    held_of INTEGER,
    tenure TEXT COLLATE NOCASE NOT NULL DEFAULT '',
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (barony_id) REFERENCES game_baronies (id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES game_barony_parts (id) ON DELETE SET NULL,
    FOREIGN KEY (held_of) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_parcels__anthro_id ON game_parcels (anthro_id);
CREATE INDEX game_parcels__barony_id ON game_parcels (barony_id);
CREATE INDEX game_parcels__part_id ON game_parcels (part_id);
CREATE INDEX game_parcels__held_of ON game_parcels (held_of);

CREATE TABLE game_preferences (
    user_id INTEGER NOT NULL,
    era TEXT COLLATE NOCASE NOT NULL DEFAULT 'dark',
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE game_proposals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    head_id INTEGER NOT NULL,
    spouse_id INTEGER NOT NULL,
    from_id INTEGER NOT NULL,
    status TEXT CHECK (status IN ('open','declined')) NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    answered_at TEXT,
    FOREIGN KEY (head_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (spouse_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (from_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);
CREATE INDEX game_proposals__status ON game_proposals (status, created_at);
CREATE INDEX game_proposals__head_id ON game_proposals (head_id);
CREATE INDEX game_proposals__spouse_id ON game_proposals (spouse_id);
CREATE INDEX game_proposals__from_id ON game_proposals (from_id);

CREATE TABLE game_ranks (
    rank INTEGER NOT NULL,
    name TEXT COLLATE NOCASE NOT NULL,
    female_name TEXT COLLATE NOCASE NOT NULL,
    is_noble INTEGER NOT NULL DEFAULT 0,
    is_hereditary INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (rank)
);

CREATE TABLE game_recipe_goods (
    recipe_id INTEGER NOT NULL,
    good TEXT COLLATE NOCASE NOT NULL,
    quantity INTEGER NOT NULL,
    role TEXT CHECK (role IN ('in','out')) NOT NULL,
    PRIMARY KEY (recipe_id, role, good),
    FOREIGN KEY (recipe_id) REFERENCES game_recipes (id) ON DELETE CASCADE,
    FOREIGN KEY (good) REFERENCES game_market_goods (good) ON DELETE CASCADE
);
CREATE INDEX game_recipe_goods__good ON game_recipe_goods (good);

CREATE TABLE game_recipes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    occupation_id INTEGER NOT NULL,
    name TEXT COLLATE NOCASE NOT NULL,
    needs_acres REAL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (occupation_id) REFERENCES game_occupations (id) ON DELETE CASCADE
);
CREATE INDEX game_recipes__occupation_id ON game_recipes (occupation_id);

CREATE TABLE game_renames (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER NOT NULL,
    old_name TEXT COLLATE NOCASE NOT NULL,
    new_name TEXT COLLATE NOCASE NOT NULL,
    renamed_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    renamed_by INTEGER,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (renamed_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_renames__anthro_id ON game_renames (anthro_id);
CREATE INDEX game_renames__renamed_by ON game_renames (renamed_by);

CREATE TABLE game_reset_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    anthro_id INTEGER,
    reason TEXT COLLATE NOCASE,
    status TEXT CHECK (status IN ('pending','done','dismissed')) NOT NULL DEFAULT 'pending',
    requested_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    handled_by INTEGER,
    handled_at TEXT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (handled_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_reset_requests__status ON game_reset_requests (status);
CREATE INDEX game_reset_requests__user_id ON game_reset_requests (user_id);
CREATE INDEX game_reset_requests__anthro_id ON game_reset_requests (anthro_id);
CREATE INDEX game_reset_requests__handled_by ON game_reset_requests (handled_by);

CREATE TABLE game_saves (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    anthros INTEGER NOT NULL,
    data BLOB NOT NULL,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX game_saves__created_by ON game_saves (created_by);

CREATE TABLE game_schedule_days (
    anthro_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    activity TEXT CHECK (activity IN ('rest','breed','work','train','clear','build','forage')) NOT NULL,
    partner_anthro_id INTEGER,
    group_id INTEGER,
    skill_id INTEGER,
    occupation_id INTEGER,
    recipe_id INTEGER,
    part_id INTEGER,
    building_id INTEGER,
    set_by INTEGER,
    PRIMARY KEY (anthro_id, day),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (partner_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (group_id) REFERENCES game_breeding_groups (id) ON DELETE SET NULL,
    FOREIGN KEY (skill_id) REFERENCES game_skills (id) ON DELETE SET NULL,
    FOREIGN KEY (set_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (occupation_id) REFERENCES game_occupations (id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES game_barony_parts (id) ON DELETE SET NULL,
    FOREIGN KEY (building_id) REFERENCES game_buildings (id) ON DELETE SET NULL,
    FOREIGN KEY (recipe_id) REFERENCES game_recipes (id) ON DELETE SET NULL
);
CREATE INDEX game_schedule_days__partner_anthro_id ON game_schedule_days (partner_anthro_id);
CREATE INDEX game_schedule_days__group_id ON game_schedule_days (group_id);
CREATE INDEX game_schedule_days__skill_id ON game_schedule_days (skill_id);
CREATE INDEX game_schedule_days__set_by ON game_schedule_days (set_by);
CREATE INDEX game_schedule_days__occupation_id ON game_schedule_days (occupation_id);
CREATE INDEX game_schedule_days__part_id ON game_schedule_days (part_id);
CREATE INDEX game_schedule_days__building_id ON game_schedule_days (building_id);
CREATE INDEX game_schedule_days__recipe_id ON game_schedule_days (recipe_id);

CREATE TABLE game_schedule_log (
    anthro_id INTEGER NOT NULL,
    day TEXT NOT NULL,
    activity TEXT CHECK (activity IN ('rest','breed','work','train','clear','build','forage','birthing')) NOT NULL,
    outcome TEXT COLLATE NOCASE,
    PRIMARY KEY (anthro_id, day),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);

CREATE TABLE game_schedule_weekly (
    anthro_id INTEGER NOT NULL,
    weekday INTEGER NOT NULL,
    activity TEXT CHECK (activity IN ('rest','breed','work','train','clear','build','forage')) NOT NULL,
    partner_anthro_id INTEGER,
    group_id INTEGER,
    skill_id INTEGER,
    occupation_id INTEGER,
    recipe_id INTEGER,
    part_id INTEGER,
    building_id INTEGER,
    set_by INTEGER,
    PRIMARY KEY (anthro_id, weekday),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (partner_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (group_id) REFERENCES game_breeding_groups (id) ON DELETE SET NULL,
    FOREIGN KEY (skill_id) REFERENCES game_skills (id) ON DELETE SET NULL,
    FOREIGN KEY (set_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (occupation_id) REFERENCES game_occupations (id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES game_barony_parts (id) ON DELETE SET NULL,
    FOREIGN KEY (building_id) REFERENCES game_buildings (id) ON DELETE SET NULL,
    FOREIGN KEY (recipe_id) REFERENCES game_recipes (id) ON DELETE SET NULL
);
CREATE INDEX game_schedule_weekly__partner_anthro_id ON game_schedule_weekly (partner_anthro_id);
CREATE INDEX game_schedule_weekly__group_id ON game_schedule_weekly (group_id);
CREATE INDEX game_schedule_weekly__skill_id ON game_schedule_weekly (skill_id);
CREATE INDEX game_schedule_weekly__set_by ON game_schedule_weekly (set_by);
CREATE INDEX game_schedule_weekly__occupation_id ON game_schedule_weekly (occupation_id);
CREATE INDEX game_schedule_weekly__part_id ON game_schedule_weekly (part_id);
CREATE INDEX game_schedule_weekly__building_id ON game_schedule_weekly (building_id);
CREATE INDEX game_schedule_weekly__recipe_id ON game_schedule_weekly (recipe_id);

CREATE TABLE game_settings (
    name TEXT COLLATE NOCASE NOT NULL,
    value TEXT COLLATE NOCASE NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE game_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    era TEXT COLLATE NOCASE,
    UNIQUE (name)
);

CREATE TABLE game_species (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    group_id INTEGER NOT NULL,
    UNIQUE (name),
    FOREIGN KEY (group_id) REFERENCES game_species_groups (id)
);
CREATE INDEX game_species__group_id ON game_species (group_id);

CREATE TABLE game_species_groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT COLLATE NOCASE NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);

CREATE TABLE game_standard_days (
    schedule_id INTEGER NOT NULL,
    weekday INTEGER NOT NULL,
    activity TEXT CHECK (activity IN ('rest','breed','work','train','clear','build','forage')) NOT NULL,
    partner_anthro_id INTEGER,
    group_id INTEGER,
    skill_id INTEGER,
    occupation_id INTEGER,
    recipe_id INTEGER,
    part_id INTEGER,
    building_id INTEGER,
    set_by INTEGER,
    PRIMARY KEY (schedule_id, weekday),
    FOREIGN KEY (schedule_id) REFERENCES game_standard_schedules (id) ON DELETE CASCADE,
    FOREIGN KEY (partner_anthro_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (group_id) REFERENCES game_breeding_groups (id) ON DELETE SET NULL,
    FOREIGN KEY (skill_id) REFERENCES game_skills (id) ON DELETE SET NULL,
    FOREIGN KEY (occupation_id) REFERENCES game_occupations (id) ON DELETE SET NULL,
    FOREIGN KEY (part_id) REFERENCES game_barony_parts (id) ON DELETE SET NULL,
    FOREIGN KEY (building_id) REFERENCES game_buildings (id) ON DELETE SET NULL,
    FOREIGN KEY (set_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (recipe_id) REFERENCES game_recipes (id) ON DELETE SET NULL
);
CREATE INDEX game_standard_days__partner_anthro_id ON game_standard_days (partner_anthro_id);
CREATE INDEX game_standard_days__group_id ON game_standard_days (group_id);
CREATE INDEX game_standard_days__skill_id ON game_standard_days (skill_id);
CREATE INDEX game_standard_days__occupation_id ON game_standard_days (occupation_id);
CREATE INDEX game_standard_days__part_id ON game_standard_days (part_id);
CREATE INDEX game_standard_days__building_id ON game_standard_days (building_id);
CREATE INDEX game_standard_days__set_by ON game_standard_days (set_by);
CREATE INDEX game_standard_days__recipe_id ON game_standard_days (recipe_id);

CREATE TABLE game_standard_schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    name TEXT COLLATE NOCASE NOT NULL,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    UNIQUE (user_id, name),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE game_transfers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    anthro_id INTEGER NOT NULL,
    from_owner_id INTEGER,
    to_owner_id INTEGER,
    transferred_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    transferred_by INTEGER,
    note TEXT COLLATE NOCASE,
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE,
    FOREIGN KEY (transferred_by) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (from_owner_id) REFERENCES game_anthros (id) ON DELETE SET NULL,
    FOREIGN KEY (to_owner_id) REFERENCES game_anthros (id) ON DELETE SET NULL
);
CREATE INDEX game_transfers__anthro_id ON game_transfers (anthro_id);
CREATE INDEX game_transfers__transferred_by ON game_transfers (transferred_by);
CREATE INDEX game_transfers__from_owner_id ON game_transfers (from_owner_id);
CREATE INDEX game_transfers__to_owner_id ON game_transfers (to_owner_id);

CREATE TABLE game_wallets (
    anthro_id INTEGER NOT NULL,
    balance INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (UTC_TIMESTAMP()),
    PRIMARY KEY (anthro_id),
    FOREIGN KEY (anthro_id) REFERENCES game_anthros (id) ON DELETE CASCADE
);
